#!/usr/bin/env bash

python train.py --data_dir 'description/NER/spacy' --save_dir 'NER/spacy' --input_encoding 'utf-8' --num_epochs 2000 --savehistory 'NER/spacy_trainingHistory.txt'
#python sample.py --n 12 --perplexity_file 'description/adsDescriptionUniqe.txt' --outcsv 'tf_word_level.csv'

# run 1
python sample.py --n 12 --prime "international" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "hotel" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "deals" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "coupon" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "reservation" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "rates" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "great" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "cost" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "expedia" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "save" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "no" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "book" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "big" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "vietnam" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "canton mA" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "best prices" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "accommodation" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "carnegie mellon university" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "guarantee" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'

# run 2
python sample.py --n 12 --prime "international" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "hotel" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "deals" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "coupon" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "reservation" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "rates" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "great" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "cost" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "expedia" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "save" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "no" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "book" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "big" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "vietnam" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "canton mA" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "best prices" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "accommodation" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "carnegie mellon university" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --prime "guarantee" --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'


# run 3 'without prime'
python sample.py --n 12 --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'
python sample.py --n 12 --perplexity_file 'description/NER/spacy/input.txt' --outcsv 'NER/spacy_tf_word_level.csv' --save_dir 'NER/spacy'